name: 自动部署到腾讯云

on:
  push:
    branches:
      - main # 只有向 main 分支提交代码时才触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 通过 SSH 部署文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "." # 要上传的文件（通常是整个项目）
          target: "/opt/1panel/www/sites/luoqi2112.com/index" # 1Panel 网站存放路径
          strip_components: 0
          timeout: 120s # 增加 2 分钟超时，防止死等
          debug: true
