name: 自动部署到腾讯云

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 智能增量部署 (Rsync)
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/opt/1panel/www/sites/luoqi2112.com/index"
          SOURCE: "./"
          # 关键配置 1：打死也不传的垃圾文件
          EXCLUDE: ".git/, .github/"
          # 关键配置 2：开启压缩、递归并删除服务器上多余的文件
          ARGS: "-avzr --delete"
